.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. x1coin_qt test_x1coin_qt
clean: FORCE
	$(MAKE) -C .. x1coin_qt_clean test_x1coin_qt_clean
check: FORCE
	$(MAKE) -C .. test_x1coin_qt_check
x1coin-qt x1coin-qt.exe: FORCE
	 $(MAKE) -C .. x1coin_qt
apk: FORCE
	$(MAKE) -C .. x1coin_qt_apk
